"""22

Revision ID: 39af0654d1ee
Revises: b9b8d24a45f7
Create Date: 2026-07-15 14:20:46.314740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39af0654d1ee'
down_revision: Union[str, Sequence[str], None] = 'b9b8d24a45f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post_Likes',
    sa.Column('postId', sa.BigInteger(), nullable=False),
    sa.Column('clientId', sa.String(length=36), nullable=False, comment='UUID'),
    sa.ForeignKeyConstraint(['postId'], ['post.postId'], name=op.f('fk_Post_Likes_postId_post')),
    sa.PrimaryKeyConstraint('postId', 'clientId', name=op.f('pk_Post_Likes'))
    )
    with op.batch_alter_table('Board', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_board_name_category', ['name', 'category'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('parentId',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('parentId',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('Board', schema=None) as batch_op:
        batch_op.drop_constraint('uq_board_name_category', type_='unique')

    op.drop_table('Post_Likes')
    # ### end Alembic commands ###
