"""first

Revision ID: b9b8d24a45f7
Revises: 
Create Date: 2026-07-15 11:36:41.417731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b8d24a45f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BaseEntity',
    sa.Column('createdAt', sa.String(length=255), nullable=True),
    sa.Column('updatedAt', sa.String(length=255), nullable=True)
    )
    op.create_table('Board',
    sa.Column('boardId', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('boardId', name=op.f('pk_Board'))
    )
    op.create_table('Tag',
    sa.Column('tagId', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tagId', name=op.f('pk_Tag'))
    )
    op.create_table('post',
    sa.Column('postId', sa.BigInteger(), nullable=False),
    sa.Column('boardId', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False, comment='UUID'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('viewCount', sa.Integer(), nullable=False),
    sa.Column('likeCount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['Board.boardId'], name=op.f('fk_post_boardId_Board')),
    sa.PrimaryKeyConstraint('postId', name=op.f('pk_post'))
    )
    op.create_table('Post_Tags',
    sa.Column('postId', sa.BigInteger(), nullable=False),
    sa.Column('tagId', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['post.postId'], name=op.f('fk_Post_Tags_postId_post')),
    sa.ForeignKeyConstraint(['tagId'], ['Tag.tagId'], name=op.f('fk_Post_Tags_tagId_Tag')),
    sa.PrimaryKeyConstraint('postId', 'tagId', name=op.f('pk_Post_Tags'))
    )
    op.create_table('comment',
    sa.Column('commentId', sa.BigInteger(), nullable=False),
    sa.Column('postId', sa.BigInteger(), nullable=False),
    sa.Column('parentId', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.String(), nullable=False, comment='UUID'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['comment.commentId'], name=op.f('fk_comment_parentId_comment')),
    sa.ForeignKeyConstraint(['postId'], ['post.postId'], name=op.f('fk_comment_postId_post')),
    sa.PrimaryKeyConstraint('commentId', name=op.f('pk_comment'))
    )
    op.create_table('media',
    sa.Column('mediaId', sa.BigInteger(), nullable=False),
    sa.Column('postId', sa.BigInteger(), nullable=False),
    sa.Column('imageUrl', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['post.postId'], name=op.f('fk_media_postId_post')),
    sa.PrimaryKeyConstraint('mediaId', name=op.f('pk_media'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('comment')
    op.drop_table('Post_Tags')
    op.drop_table('post')
    op.drop_table('Tag')
    op.drop_table('Board')
    op.drop_table('BaseEntity')
    # ### end Alembic commands ###
