@echo off
cd /d "%~dp0\.."
setlocal

if /i "%~1"=="--help" goto help

:menu
cls
echo ==========================================
echo     Busan LocalHub Database Manager
echo ==========================================
echo 1. Create an autogenerated migration
echo 2. Upgrade database to head
echo 3. Show current revision and history
echo 4. Stamp database as head
echo 5. Reset Alembic revision to base
echo 6. Exit
echo ==========================================
set /p choice="Select an option: "

if "%choice%"=="1" goto revision
if "%choice%"=="2" goto upgrade
if "%choice%"=="3" goto status
if "%choice%"=="4" goto stamp
if "%choice%"=="5" goto reset_version
if "%choice%"=="6" exit /b 0
goto menu

:revision
set /p msg="Migration message: "
if "%msg%"=="" (
    echo Cancelled: migration message is required.
) else (
    call uv run alembic revision --autogenerate -m "%msg%"
)
pause
goto menu

:upgrade
call uv run alembic upgrade head
pause
goto menu

:status
echo.
echo [Current revision]
call uv run alembic current
echo.
echo [Migration history]
call uv run alembic history
pause
goto menu

:stamp
echo WARNING: This changes revision metadata without changing the schema.
set /p confirm="Continue? (y/N): "
if /i "%confirm%"=="y" (
    call uv run alembic stamp head
) else (
    echo Cancelled.
)
pause
goto menu

:reset_version
echo WARNING: This resets Alembic revision metadata without changing the schema.
call uv run python scripts/reset_alembic_version.py
pause
goto menu

:help
echo Usage: scripts\manage_db.bat
echo.
echo Opens an interactive menu for Alembic revision, upgrade, status,
echo stamp, and revision reset operations.
exit /b 0
